SystemAndDistribution:
  node: 34
  power_factor: 0.2
  std: 10 # standard deviation of power injection noise
  save_path: 'src/powersystems/psdistribution/34node'
  batch_size: 20000
  n_components: 5 # number of Gaussian components
  dis_path: 'src/powersystems/psdistribution/34node/gmm_power.pkl'
  scaler_path: 'src/powersystems/psdistribution/34node/scalers.pkl'
  mean_vector_start: 50

CNice:
  # Model parameters
  split_ratio:  0.5
  n_blocks:  4
  hiddemen_dim:  256
  c_dim:  66
  n_layers:  4
  input_dim:  2  # Assuming each node has a real and imaginary part
  hiddemen_dim_condition:  256
  output_dim_condition:  1
  n_layers_condition:  3

  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/cnice/savedmodel'


CRealnvp:
  # Model parameters
  split_ratio:  0.5
  n_blocks:  4
  hiddemen_dim:  256
  c_dim:  66
  n_layers:  3
  input_dim:  2  # Assuming each node has a real and imaginary part
  hiddemen_dim_condition:  256
  output_dim_condition:  1
  n_layers_condition:  3

  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/crealnvp/savedmodel'
  forward_loss_ratio:  0.5

CSpline:
  # Input parameters
  input_dim:  2
  c_dim:  66
  hiddemen_dim:  256

  # Model features main
  split_ratio:  0.5
  n_blocks:  5
  n_layers:  3

  # Model Features condition
  hiddemen_dim_condition:  256
  n_layers_condition:  3
  b_interval: 6
  k_bins:  10

  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/cspline/savedmodel'
  forward_loss_ratio:  0.5

Gnn:
  # Input parameters
  c_dim:  66
  hiddemen_dim: 860
  
  # Model features main
  n_layers:  7

  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/gnn/savedmodel'

NN:
  # Input parameters
  c_dim:  66
  hiddemen_dim:  860
  n_layers : 7


  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/nn/savedmodel'

MixedSplineNVP:
# Input parameters
  input_dim:  2
  c_dim:  66
  hiddemen_dim:  256

  # Model features main
  split_ratio:  0.5
  n_blocks_spline: 3
  n_blocks_realnvp: 2
  n_layers:  3

  # Model Features condition
  hiddemen_dim_condition:  200
  n_layers_condition:  3
  b_interval: 6
  k_bins:  10

  # Training parameters
  learning_rate:  0.0001
  batch_size:  1000
  lr: 0.001
  epochs: 500000
  save_path:  'src/training/mixedsplinenvp/savedmodel'
  forward_loss_ratio:  0.5
