SystemAndDistribution:
  node: 34
  power_factor: 0.2
  std: 10 # standard deviation of power injection noise
  save_path: 'src/powersystems/psdistribution/34node'
  batch_size: 20000
  n_components: 5 # number of Gaussian components
  dis_path: 'src/powersystems/psdistribution/34node/gmm_power.pkl'
  sacler_path: 'src/powersystems/psdistribution/34node/scalers.pkl'
  mean_vector_start: 50

NICE:
  # 
  num_nodes: 34
  num_children: 3
  power_factor: 0.2

  split_ratio: 0.6
  n_blocks: 4
  hiddemen_dim: 256
  n_layers: 2
  full_dim: 66  # (num_nodes - 1) * 2

  batch_size: 500
  epochs: 2000
