NICE:
  # 
  num_nodes: 34
  num_children: 3
  power_factor: 0.2

  split_ratio: 0.6
  n_blocks: 4
  hiddemen_dim: 256
  n_layers: 2
  full_dim: 66  # (num_nodes - 1) * 2

  batch_size: 500
  epochs: 2000
